import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HeaderComponent from "../components/common/header";
import FloatingLabel from 'react-bootstrap/FloatingLabel';
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import { useState } from "react";


const options = [
   { id: 1, name: "Validar todos os schemas/espaços no INSTALL" },
   { id: 2, name: "Validar todos os schemas/espaços no ROLLBACK" },
   { id: 3, name: "Validar deletes nos Pacotes" },
   { id: 4, name: "Pesquisar palavra coringa no INSTALL" },
   { id: 5, name: "Pesquisar palavra coringa no ROLLBACK" }
 ];


function uncheckAll(options) {
   return options.map((option) => ({
     ...option,
     checked: false
   }));
 }

 function toggleOption(id, checked) {
   return options.map((option) =>
     option.id === id ? { ...option, checked } : option
   );
 }


export default function Checa(){


   const [checkedList, setCheckedList] = useState(options);
   const changeList = (id, checked) => {
     const newCheckedList = toggleOption(id, checked);
     setCheckedList(newCheckedList);
   };

   return (
      <>
      
      <Head>
        <title>Projeto X</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
         <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
         <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,700;1,400&display=swap" rel="stylesheet"/>
      </Head>
      <HeaderComponent></HeaderComponent>
      <main className={styles.main}> 
          <h1>Tela Checa Pacotes</h1>
         <div className={styles.form_checa}>
         <form className={styles.form_checa}>
            {checkedList.map(({ id, name, checked }) => (
               <label key={id}>
               <input
                  type="radio"
                  name="options"
                  className={styles.label}
                  value={id}
                  checked={checked}
                  onChange={(e) => changeList(id, e.target.checked)}
               />
               {name}
               </label>
            ))}
                <Form.Group controlId="formFile">
        <Form.Label></Form.Label>
        <Form.Control  className={styles.mbr} type="file" />
        <Button  className={styles.button_checa}>Submit</Button>
      </Form.Group>
          </form>
         </div>

      </main>
        </>
   ) 
}