import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HeaderComponent from "../components/common/header";
import Dropdown from 'react-bootstrap/Dropdown';
import DropdownButton from 'react-bootstrap/DropdownButton';

export default function Gerador(){
    return (
         <>
      <Head>
        <title>Projeto X</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
         <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
         <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,700;1,400&display=swap" rel="stylesheet"/>
      </Head>
      <HeaderComponent></HeaderComponent>
      <div  className={styles.dropdown}>
      <h1>Tela Gerador de estrutura</h1>
         <h2>Selecione o tipo de estrutura que você gostaria de gerar</h2>
      <DropdownButton id="dropdown-basic-button" title="Dropdown button" className={styles.gerador}>
      <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
      <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
      <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
    </DropdownButton>
      </div>
      <main className={styles.main}> 

      </main>
         </>
    ) 
 }